-- ============================================================
-- 東方智慧詮釋多語言資料匯入（en/ja/ko/zh-CN）
-- 執行方式：在 Supabase SQL Editor 中執行
-- ============================================================

INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (0, 'The Fool', 'upright', 'Like the hidden dragon of the first line of the Qian hexagram in the I Ching, you''re standing at a brand-new starting point, carrying pure trust and infinite possibility. Eastern wisdom tells you: the true Dao begins with knowing by not knowing. Right now there''s no need to over-plan—just follow your inner intuition and move forward. Every seemingly adventurous step is a step toward awakening. Let go of your attachment to results, enjoy the experience of the present moment, and this innocence is exactly your most precious strength.', 'en'),
  (0, 'The Fool', 'reversed', 'The reversed Fool reminds you: you may have drifted off the Dao through excessive recklessness, or fear of the unknown keeps you stuck in place. Eastern wisdom teaches "know when to stop, and only then can you find stillness"—what''s needed now is restraint, not charging ahead blindly. Stop first, observe where your impulses come from, recalibrate your direction, and then take the next step with a clear mind.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (1, 'The Magician', 'upright', 'In Eastern wisdom, the Magician is like the creative force of "Tai Chi giving birth to the Two Forms"—you already hold the vital energy of heaven and earth in your hands; everything is in place. Taoism speaks of Wu Wei, effortless action: when your intention, your action, and your resources become one, creation happens naturally. This is the moment to turn inner wisdom into outer reality. Trust your abilities, let the energy flow downstream, and all things are within reach.', 'en'),
  (1, 'The Magician', 'reversed', 'The reversed Magician suggests: your energy isn''t flowing through, or your intention isn''t pure, and creation is being blocked. As the Meng hexagram in the I Ching shows, you must first enlighten and correct your mind before you can move forward. Examine your motives and methods—are you over-manipulating, rushing for results? Return to the state of "empty the mind to the utmost, guard stillness firmly," and let inner wisdom lead again instead of clinging to technique.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (2, 'The High Priestess', 'upright', 'The High Priestess embodies the Taoist way of "quiet contemplation"—you are in a state of inner stillness and open intuition. Eastern wisdom says "empty the mind to the utmost, guard stillness firmly; all things arise together, and I watch them return." No need to seek answers outward right now—the answer is already at the bottom of your heart. Sit in stillness, meditate, listen to the small inner voice. The wisdom that remains hidden is waiting for you to meet it in the quiet.', 'en'),
  (2, 'The High Priestess', 'reversed', 'The reversed High Priestess reminds you: you may have lost touch with your inner intuition, your inner voice drowned out by the noise of the outside world. Like the perilous Kan hexagram in the I Ching, when the lake of the mind is stirred, its reflection becomes distorted. Find your space of silence again, let go of excessive thinking and worry, and return your mind to a mirror-like state—then true perception will surface once more.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (3, 'The Empress', 'upright', 'The Empress embodies the Eastern wisdom of "thick virtue carries all things"—the abundance and nourishment of the Earth Mother. You are in a season of harvest and growth, as the Kun hexagram says: "The earth''s terrain is kun; the noble person nurtures all things with thick virtue." Open yourself to receive the gifts life is offering, savor the richness of the present, and use that abundance to nourish the people around you. Flow with nature''s rhythm and let life bloom like a flower.', 'en'),
  (3, 'The Empress', 'reversed', 'The reversed Empress reminds you: you may be disconnected from your source of nourishment, giving too much while ignoring your own needs. Like the earth losing its rain, life begins to wither. Take care of yourself first—your body, your emotions, your heart''s needs. Only when you yourself are full can you truly give. Return to the embrace of nature and reconnect with that unconditional love and nourishment.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (4, 'The Emperor', 'upright', 'In Eastern wisdom, the Emperor symbolizes the leadership of "strength, correctness, and centeredness," like the Qian hexagram''s "ceaseless self-renewal." You are at a moment of establishing order and building structure—your decisiveness and principles bring stability to the situation. Though Taoism speaks of Wu Wei, where structure is needed, clear boundaries and steady discipline are precisely the Dao made manifest. Lead with fairness and stability.', 'en'),
  (4, 'The Emperor', 'reversed', 'The reversed Emperor reminds you: excessive control or rigid rules have become a cage that binds you. As the Guai hexagram shows, stubborn self-will eventually brings loss. Eastern wisdom teaches "softness overcomes hardness"—what''s needed now is to let go of fixed attachments and allow flexibility and adaptation. True power lies not in gripping tightly, but in the wisdom of bending and stretching.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (5, 'The Hierophant', 'upright', 'The Hierophant is like the Eastern "way of the teacher"—you are in a phase of learning and passing on tradition, and the wisdom of tradition lights your path ahead. Taoism says "the Dao follows nature," and on the road to the Dao, the guidance of good teachers is precious. Humbly seek guidance now and follow time-tested principles, while remembering that "believing everything in books is worse than having no books"—keep room for your own direct realization within the tradition.', 'en'),
  (5, 'The Hierophant', 'reversed', 'The reversed Hierophant reminds you: you may be overly attached to existing frameworks, or you''ve begun to doubt the dogmas of authority. Like Zen''s spirit of "not relying on words and letters, pointing directly to the mind"—the true Dao lives not in forms but in your own firsthand experience. Listen to the voice within, break through rigid dogma, and find a path that is truly yours—without needing to reject the value of tradition entirely.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (6, 'The Lovers', 'upright', 'In Eastern wisdom, the Lovers embody the way of "yin and yang uniting in harmony"—opposing forces achieve a complete fusion at this moment. You are facing an important choice, and the key to this choice lies in "oneness": alignment with your inner values, harmonious resonance with others. Taoism says "all things carry yin and embrace yang"—true harmony is not the elimination of difference, but letting different forces bring out the best in each other.', 'en'),
  (6, 'The Lovers', 'reversed', 'The reversed Lovers remind you: your inner values are in conflict, and the two ends of the choice are tearing you apart. As the Kui hexagram in the I Ching shows, amid estrangement and opposition you need to seek a new balance. Return to the center of your heart first, clarify what truly matters to you, find the possibility of unity within the contradiction, and let the divided energies reconcile.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (7, 'The Chariot', 'upright', 'The Chariot embodies the Eastern wisdom of "mastery and steering"—like the Shi hexagram''s art of leading the many, using righteousness to command momentum and stillness to control movement. You are at a moment that demands firm will and a steady hand on direction. The road ahead holds challenges, but as long as your goal is clear and your mind is single-focused, you can advance as steadily as a charioteer. Use gentleness to rein in force; use stillness to meet change.', 'en'),
  (7, 'The Chariot', 'reversed', 'The reversed Chariot reminds you: you may have lost your direction, or be trapped by inner contradictions, leaving your energy scattered and your progress faltering. Eastern wisdom says "knowing when to stop keeps you from danger"—when you don''t know where to go, stopping is also a way of moving forward. First settle the conflicts within, re-establish your goal, and let your will and your actions become one again.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (8, 'Strength', 'upright', 'In Eastern wisdom, Strength is not confrontation but the taming art of "softness overcoming hardness"—like the Taoist taming a tiger, not with brute force but with inner stillness and calm. You are showing true courage right now: facing the beast within (fear, desire, impulse), not by suppressing or fighting it, but by gently accepting and guiding it. This inner peace is precisely the greatest power there is.', 'en'),
  (8, 'Strength', 'reversed', 'The reversed Strength reminds you: you may be wrestling with some force within yourself, or losing faith in yourself. Eastern wisdom says "softness overcomes hardness"—hitting hardness with hardness only wears you down. Stop the fight first, look at your fears and weaknesses with compassion, and within that acceptance, rediscover the gentle yet steady strength that is yours.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (9, 'The Hermit', 'upright', 'The Hermit is like the Eastern recluse—you are in a phase of solitude and inner reflection, the necessary road to wisdom. Taoism says "learning daily increases; practicing the Dao daily decreases"—this solitude is not escape, but stripping away the glitter of the outer world to return to what is real within. Walking alone with a lamp is to illuminate yourself, and to see clearly the path that is truly yours.', 'en'),
  (9, 'The Hermit', 'reversed', 'The reversed Hermit reminds you: you may be overly closed off, or refusing to face the loneliness inside, letting solitude turn into isolation. Eastern wisdom speaks of "harmonizing your light with the dust of the world"—a true practitioner does not leave the world, but keeps the heart clear while living amid it. Find balance between solitude and connection, and let your introspection become wisdom in action rather than an excuse for avoidance.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (10, 'Wheel of Fortune', 'upright', 'In Eastern wisdom, the Wheel of Fortune is like "the waxing and waning of yin and yang, the cycle of the heavenly Dao"—all things have their season; at the peak decline begins, and at the bottom fortune turns. You are at a natural turning point, and everything that happens carries deeper meaning. Taoism says "go with the flow"—the best attitude now is not to resist change but to follow the Dao of heaven, keeping your heart steady as the wheel turns, accepting what cannot be changed and resting at peace with fate.', 'en'),
  (10, 'Wheel of Fortune', 'reversed', 'The reversed Wheel of Fortune reminds you: you may feel fortune is against you, or you are resisting the unavoidable changes of life. As the Bo hexagram shows, when yin grows and yang recedes, you must hold to what is right and wait for the time. Eastern wisdom says "when the old man at the frontier loses his horse, who knows if it''s a blessing"—this reversal may be the beginning of a turn for the better. Keep patience and faith, flow with the cycle, and wait for your moment to come.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (11, 'Justice', 'upright', 'In Eastern wisdom, Justice is like "the heavenly Dao has no favorites, yet always sides with the good"—cause and effect are exact, never missing by a hair. You are facing a moment that calls for fair judgment, and that judgment should come from inner clarity and conscience. Taoism speaks of "governing through non-action"—true justice is not human arbitration but the natural result of following the Dao''s laws. Act with a fair heart, and a clear conscience is the open road.', 'en'),
  (11, 'Justice', 'reversed', 'The reversed Justice reminds you: you may be facing imbalance or injustice, or carrying something on your conscience that keeps you from feeling at ease. Eastern wisdom says "you reap what you sow"—rather than blaming heaven and others, look back into your own causes and effects. Face your choices and responsibilities honestly, correct what is out of balance, and return your heart to a centered, peaceful place.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (12, 'The Hanged Man', 'upright', 'The Hanged Man holds the deep meaning of "the movement of the Dao reverses"—what looks like stagnation is actually retreating in order to advance; what looks like sacrifice actually buys a new perspective. You are at a moment that asks you to let go of attachments and shift your viewpoint. Taoism says "the crooked becomes whole, the bent becomes straight"—sometimes you have to see the world upside down to see the truth. This "hanging" is a necessary stillness that lets energy flow again.', 'en'),
  (12, 'The Hanged Man', 'reversed', 'The reversed Hanged Man reminds you: you may be suffering for nothing, enduring hardship without gaining any insight from it; or you refuse the necessary letting-go, insisting on moving forward the old way. Eastern wisdom speaks of "giving and gaining"—only by letting go can you receive. Examine what you are clutching so tightly—has that grip become your shackle? The moment you are willing to open your hands is the moment the turn begins.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (13, 'Death', 'upright', 'In Eastern wisdom, Death is not an ending but the transformation of "endless generation"—like the rotation of the seasons and the withering and blooming of plants, the old form fades precisely to make way for new life. You are in a deep phase of transformation, and the ending is necessary, like a snake shedding its old skin. Taoism says "only by not being full can one be renewed from the worn-out"—let go of the old self to welcome new life.', 'en'),
  (13, 'Death', 'reversed', 'The reversed Death reminds you: you may be resisting a necessary ending, clinging to people and things that have already withered, and your life energy is stagnating because of it. As the Ge hexagram shows, the change that follows heaven and answers people is unavoidable. Eastern wisdom says "when the way is exhausted, change; with change comes passage"—bravely accept that this phase is complete, free yourself from the past, and only then can new possibilities flow in.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (14, 'Temperance', 'upright', 'Temperance embodies the Eastern wisdom of the "Middle Way"—neither biased nor excessive, just right. You are at a stage that calls for harmonizing and balancing, like the completeness of the Ji Ji hexagram, and like the perfect interweaving of yin and yang in the Tai Chi diagram. Taoism says "know contentment and avoid disgrace; know when to stop and avoid danger"—act by the middle way now, letting opposing forces temper each other, like water moistening all things: gentle yet enduring.', 'en'),
  (14, 'Temperance', 'reversed', 'The reversed Temperance reminds you: you may be in a state of imbalance—too much or too little, robbing life of its harmony. Eastern wisdom says "going too far is the same as falling short"—what''s needed now is to recalibrate your rhythm and proportions. Look at which aspect of life has lost its balance (work and rest, giving and receiving, reason and emotion), return to the middle way, and let the energy flow again.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (15, 'The Devil', 'upright', 'In Eastern wisdom, the Devil is like the "mind demon"—the bonds of attachment, greed, and ignorance. You are bound by some intense desire or habitual pattern, and the chain that binds you is one you can actually lay down. Taoism says "the five colors blind the eyes, the five tones deafen the ears"—awareness is the beginning of liberation. See the nature of your attachment clearly, and you are already walking the road to freedom.', 'en'),
  (15, 'The Devil', 'reversed', 'The reversed Devil is a sign of liberation—you are breaking free from your bonds and reclaiming command of your own life. Like Zen''s "when the wild mind suddenly stops, the stopping itself is awakening"—once you realize the shackles are only illusory projections, they begin to crumble. Now, firmly cut the chains of attachment, but also be gentle with yourself, because the process of growth calls for compassion.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (16, 'The Tower', 'upright', 'The Tower is like the thunder of the Zhen hexagram in the I Ching—a sudden jolt that shatters false stability. You are going through an upheaval that looks destructive but is actually drawing the final line under an illusory structure. Taoism says "a whirlwind does not last all morning, a downpour does not last all day"—after great upheaval, stillness always returns. Trust the process: what was shaken loose were the parts that were no longer true, and the real you will be reborn from the ruins.', 'en'),
  (16, 'The Tower', 'reversed', 'The reversed Tower reminds you: you may be desperately trying to avoid a necessary collapse, or the impact of the disaster has passed and you are rebuilding amid the aftermath. Eastern wisdom says "misfortune is where fortune leans"—what looks like catastrophe often hides a turning point. Stop patching up the crumbling old structure; allow the necessary dismantling so that a truer, more solid foundation can be built.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (17, 'The Star', 'upright', 'The Star is like the North Star guiding the Eastern night sky—after chaos and darkness, the light of hope rises again. You are in a phase of healing and rebirth, and your inner longing shines as pure and bright as starlight. Taoism says "the highest good is like water"—face the future with gentleness and faith now, trust in the kindness of the universe, and let the light of hope carry you through confusion toward clarity.', 'en'),
  (17, 'The Star', 'reversed', 'The reversed Star reminds you: you may be feeling hope is slim, or losing faith in the future, your inner light veiled by clouds. Eastern wisdom says "heaven moves with vigor; the noble person strives ceaselessly"—even in the deepest night, the stars are still there. Don''t give up your inner faith; find hope again first in the small things, and let that spark of starlight rekindle your journey.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (18, 'The Moon', 'upright', 'The Moon holds the mystery of "yin" in Eastern wisdom—the subconscious, illusion, and the yet-unseen. You are in a vague, unclear phase, and what lies before you may not be what it appears to be. Taoism says "dim and obscure, yet within it there are images"—beneath the moon, truth remains hidden. Don''t rush to judgment now; trust your intuition, but also stay aware, and wait until the clouds part and the moon is clear before you decide.', 'en'),
  (18, 'The Moon', 'reversed', 'The reversed Moon is a sign that the fog is lifting—you are emerging from illusion and fear, and the truth is gradually revealing itself. Like the Ming Yi hexagram''s "advantage in hardship and perseverance," the dark night is nearly over and dawn is approaching. Keep staying aware—the things that once frightened you often prove not so frightening once you see them clearly. When you pass through your inner confusion, you gain a deeper clarity.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (19, 'The Sun', 'upright', 'The Sun is the radiant peak of "yang"—all things made visible, brimming with vitality. You are in a bright and abundant period, full of energy, and what you put your hand to manifests. Taoism speaks of the way of "yang brightness"—open your heart now, fully enjoy the beauty and warmth of life, and use this light to brighten others as well. Flow with this upward energy and let it bloom naturally.', 'en'),
  (19, 'The Sun', 'reversed', 'The reversed Sun reminds you: the light may be temporarily veiled, or you are overdoing the brilliance and losing sight of inner balance. Eastern wisdom says "the arrogant dragon has regrets"—when yang reaches its peak, yin begins to grow; too much light can also burn yourself. Stay humble within joy, remember to return to inner stillness amid achievement, and let the sunlight both warm others and illuminate yourself.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (20, 'Judgement', 'upright', 'Judgement is like the "return of one yang" in the Fu hexagram of the I Ching—the call of awakening and rebirth. You are facing a profound inner calling; past experiences are being re-examined and integrated at this moment, gaining new meaning. Taoism speaks of "returning to the root and the source"—this is a time of reunion with your true self. Listen to the call within, forgive the past, welcome rebirth, and let life enter a new chapter.', 'en'),
  (20, 'Judgement', 'reversed', 'The reversed Judgement reminds you: you may be resisting the call within, or unable to forgive yourself and others, letting the past become baggage that weighs down your journey. Eastern wisdom says "drop the butcher''s knife and become a Buddha on the spot"—awakening lives only in the present thought. Stop judging yourself, and allow yourself to begin again. The moment you are willing to honestly face the voice inside, you are already on the road to rebirth.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (21, 'The World', 'upright', 'The World is like the completeness that follows Ji Ji in the I Ching, and like the completion of the Tai Chi—the perfect completion of a cycle. You are at a stage of fulfillment and integration; the efforts of the past are now bearing fruit. Taoism speaks of "retiring after success"—completion is not stagnation, but the preparation for a new cycle. First fully experience this achievement and wholeness, then with a clear mind, set out on the next journey.', 'en'),
  (21, 'The World', 'reversed', 'The reversed World reminds you: you may be close to completion yet unable to finish, or feel uneasy about the "completion" that is approaching. Eastern wisdom says "when things reach their extreme they reverse, circling round and round"—completion is not an endpoint but the starting point of the next cycle. Look at what is making you hesitate at the last step, let go of your attachment to "perfection," bravely cross the finish line, and welcome the new beginning.', 'en');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (0, '愚者', 'upright', '易経「乾卦」の初九に登場する潜龍のように、あなたは今、まったく新しい出発点に立っています。純粋な信頼と無限の可能性を携えて。東洋の智慧はこう教えてくれます——本当の道は、「知らないことを知る」ことから始まると。今は過度に計画を立てる必要はありません。内なる直感に従って進んでください。危険に思える一歩一歩も、すべて覚醒へと続く道なのです。結果へのこだわりを手放し、今この瞬間の体験を楽しんでください。その天真らしさこそが、あなたの最も貴重な力なのです。', 'ja'),
  (0, '愚者', 'reversed', '逆位の愚者はこう教えてくれます。あなたはあまりに無鉄砲なあまり道を外れているのかもしれません。あるいは、未知への恐れから立ち止まったままになっているのかもしれません。東洋の智慧は「止まることを知ってこそ、安定が生まれる」という教えを大切にします。今必要なのは突進ではなく、収斂です。まず立ち止まり、自分の衝動がどこから来ているのかを静かに観察し、方向性を整え直してから、澄んだ心で次の一歩を踏み出してください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (1, '魔術師', 'upright', '魔術師は、東洋の智慧でいえば「太極が両儀を生む」創造の力です——あなたの手にはすでに天地の気が宿り、すべてが整っています。道家は「無為にして為す」と説きます。意図・行動・資源の三者がひとつになるとき、創造は自然に起こります。今まさに、内なる智慧を外の現実に具現化するとき。自分の力を信じ、エネルギーを流れに委ねてください。すべては成し遂げられます。', 'ja'),
  (1, '魔術師', 'reversed', '逆位の魔術師はこう示しています。エネルギーが通じていないか、意図が純粋でないために、創造が滞っているのです。易経「蒙卦」が示すように、まず心を啓き正してから、初めて道に通じることができます。自分の動機と方法を見つめ直してください——過度に操作していませんか？結果を急いでいませんか？「虚を極め、静を篤く守る」の状態に立ち返り、技巧に固執するのではなく、内なる智慧に再び主導権を委ねてください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (2, '女教皇', 'upright', '女教皇は、道家のいう「静観」の道のような存在です——あなたは今、内なる静けさと直感が通じる状態にあります。東洋の智慧は「虚を極め、静を篤く守る」——万物が共に働くなか、私はそれを見つめ、巡りを観るのだ、と説きます。今は外に答えを求める必要はありません。答えはすでにあなたの心の奥底にあるのです。静かに座し、瞑想し、内なる微かな声に耳を傾けてください。まだ顕れていない智慧が、静けさのなかであなたとの出会いを待っています。', 'ja'),
  (2, '女教皇', 'reversed', '逆位の女教皇はこう教えてくれます。あなたは内なる直感とのつながりを失い、外の喧騒に心の声をかき消されているのかもしれません。易経「坎卦」が示す深い陥穽のように、心の水面が揺れれば映るものも歪みます。もう一度、静けさの空間を取り戻してください。過剰な思慮や心配を手放し、心を鏡のように澄んだ状態に戻せば、本当の感覚が再び浮かび上がってきます。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (3, '女帝', 'upright', '女帝は、東洋の智慧における「深い徳が万物を支える」という教えを体現しています——大地の母としての豊かさと慈愛。あなたは今、収穫と成長の季節にいます。坤卦の「地の勢いは坤、君子は厚い徳をもって万物を載せる」のとおりです。今は、生命が与えてくれる贈り物を開かれた心で受け取り、今この瞬間の豊かさを味わってください。同時に、その豊かさで周りの人々を慈しんでください。自然のリズムに身を任せ、生命が花のように咲き誇るのを許してください。', 'ja'),
  (3, '女帝', 'reversed', '逆位の女帝はこう教えてくれます。あなたは慈愛の源から離れ、与えすぎて自分の必要をないがしろにしているのかもしれません。大地が雨を失えば、生命は枯れていきます。まず自分自身を大切にしてください——身体・感情・心の必要を。自分が満たされてこそ、本当に与えることができるのです。自然の懐に帰り、無条件の愛と慈愛とのつながりを再び取り戻してください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (4, '皇帝', 'upright', '皇帝は、東洋の智慧において「剛健にして中正」のリーダーシップを象徴します。乾卦のいう「自ら強く、休むことなく努める」のように。あなたは今、秩序を築き、構造を確立するときを迎えています。あなたの決断と原則が、状況に安定をもたらす力となっています。道家は無為を説きますが、構造が必要な場所では、明確な境界と規律こそが「道」の顕れなのです。公正さと安定をもって、前へ導いてください。', 'ja'),
  (4, '皇帝', 'reversed', '逆位の皇帝はこう教えてくれます。過度な支配や硬直した規則が、かえって自分を縛る檻になっているかもしれません。易経「夬卦」が示すように、自分の考えに固執することは、ついには損を招きます。東洋の智慧は「柔弱は剛強に勝る」と説きます。今必要なのは執着を手放し、融通と弾力性を許すことです。本当の力は握りしめることではなく、曲がることも伸びることもできる智慧のなかにあるのです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (5, '教皇', 'upright', '教皇は、東洋における「師の道」のような存在です——あなたは今、伝承と学びの段階にあり、伝統の智慧があなたの行く手を照らしています。道家は「道は自然に法る」と説きますが、道へ至る道のりでは、善き導き手の存在はかけがえのないものです。今は虚心に教えを請い、長い時間を経て検証されてきた法則に従いつつも、「書物をすべて信じるよりは、書物のないほうがまし」という言葉も忘れないでください。伝承のなかにも、自分自身で体得する余地を残しておくのです。', 'ja'),
  (5, '教皇', 'reversed', '逆位の教皇はこう教えてくれます。あなたは既存の枠組みに過度に依存しているか、権威の教義に疑問を抱き始めているのかもしれません。禅宗の「文字を立てず、直接人の心を指す」という精神のように——本当の道は形式のなかにあるのではなく、あなた自身の体験のなかにあるのです。内なる声に耳を傾け、硬直した教義を超えて、あなた自身の道を見つけてください。ただし、伝統の価値をすべて否定する必要はありません。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (6, '恋人', 'upright', '恋人は、東洋の智慧でいえば「陰陽和合」の道です——対立する力が、このとき完璧な融合を遂げます。あなたは今、大切な選択に直面しています。そしてこの選択の鍵は「合一」にあります——内なる価値観との一致、他者との調和の共鳴。道家は「万物は陰を負いて陽を抱く」と説きます。本当の調和とは差異を消し去ることではなく、異なる力が互いに成就し合うことなのです。', 'ja'),
  (6, '恋人', 'reversed', '逆位の恋人はこう教えてくれます。内なる価値観が衝突し、選択の両極に引き裂かれているように感じるかもしれません。易経「睽卦」が示すように、背離と対立のなかで、新しい均衡を探す必要があります。まず心の中心に立ち返り、あなたにとって本当に大切なものが何かを明らかにしてください。矛盾のなかで統合の可能性を探し、分裂したエネルギーを再び和解させてください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (7, '戦車', 'upright', '戦車は、東洋の智慧における「馭する道」を体現しています——易経「師卦」の衆を治める術のように、正をもって勢いを御し、静をもって動を制します。あなたは今、確固たる意志と方向性の掌握が求められる時を迎えています。前方の道には挑戦があるかもしれませんが、目標が明確で心がひとつに定まっていれば、車を操るように安定して進むことができます。柔をもって剛を馭し、定をもって変化に応じるのです。', 'ja'),
  (7, '戦車', 'reversed', '逆位の戦車はこう教えてくれます。あなたは方向を見失っているか、内なる矛盾に囚われて、エネルギーが散漫になり進退窮まっているのかもしれません。東洋の智慧は「止まることを知れば危うくない」と説きます——どこへ向かうべきか分からないとき、立ち止まることもまた前進のひとつの形なのです。まず内なる葛藤を鎮め、目標を立て直し、意志と行動を再びひとつにしてください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (8, '力', 'upright', '力は、東洋の智慧においては対抗ではなく、「柔よく剛を制す」馴化の道です——道家が虎を馭するように、腕力ではなく内なる静定によって。あなたは今、本当の勇気を発揮しています。内なる猛獣（恐れ・欲望・衝動）に向き合うとき、それは抑圧したり戦ったりすることではなく、優しく受け入れ導くことなのです。この内なる平和こそが、最も強い力なのです。', 'ja'),
  (8, '力', 'reversed', '逆位の力はこう教えてくれます。あなたは内なる何かの力と格闘しているか、自分自身への信頼を失っているのかもしれません。東洋の智慧は「柔弱は剛強に勝る」と説きます。真正面からぶつかり合えば、自分を消耗させるだけです。まず対抗をやめ、慈しみの心で自分の恐れや弱さを見つめてください。受け入れるなかで、あの優しくも確固たる力を再び見つけられるはずです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (9, '隠者', 'upright', '隠者は、東洋における「隠者」のような存在です——あなたは今、独りでいることと内省の段階にあり、これは智慧へ至るために必ず通る道なのです。道家は「学びを為すは日に益し、道を為すは日に損す」と説きます。今の独りは逃避ではなく、外の華やかさを削ぎ落とし、内なる真実へ立ち返ることなのです。灯りを掲げて独り歩くのは、自分自身を照らすためであり、本当の自分の道を見極めるためでもあります。', 'ja'),
  (9, '隠者', 'reversed', '逆位の隠者はこう教えてくれます。あなたは過度に閉じこもっているか、内なる孤独と向き合うことを拒み、独りが隔離になってしまっているのかもしれません。東洋の智慧は「光を和らげ、塵に同化する」と説きます——本当の修行者は世間を離れず、俗世のなかで内なる清らかさを保つのです。独りとつながりのあいだでバランスを取り、内省を行動の智慧に変えてください。逃避の言い訳にしてはいけません。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (10, '運命の輪', 'upright', '運命の輪は、東洋の智慧では「陰陽の消長、天道の循環」のようなものです——万物にはすべて時があり、盛ん極まれば衰え、窮まれば泰に転じます。あなたは今、自然な転換点に立っています。起こるすべてのことに深い意味があります。道家は「自然に順う」と説きます。今いちばん良い態度は、変化に抗うことではなく、天道に従うこと。輪の回転のなかで内なる安定を保ち、抗えないことを知り、それを運命として静かに受け入れてください。', 'ja'),
  (10, '運命の輪', 'reversed', '逆位の運命の輪はこう教えてくれます。あなたは運が向いていないと感じているか、避けられない人生の変化に抗っているのかもしれません。易経「剝卦」が示すように、陰が伸び陽が衰えるときこそ、正を守りながら時を待つことが大切です。東洋の智慧は「塞翁の馬、どうして福でないと分かるだろうか」と説きます——今の逆転こそ、転機の始まりかもしれません。忍耐と信頼を保ち、循環に身を任せ、時が来るのを待ってください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (11, '正義', 'upright', '正義は、東洋の智慧における「天道は親なし、常に善人に与う」のようなものです——因果は偽りなく、少しの狂いもありません。あなたは今、公正な判断が求められる時に直面しています。そしてその判断は、心の清らかさと良知から生まれるべきものです。道家は「無為にして治まる」と説きます。本当の公義は人の手による裁量ではなく、自然の法則に従った結果なのです。公正な心で行動し、良心に恥じるところがなければ、それが平坦な道なのです。', 'ja'),
  (11, '正義', 'reversed', '逆位の正義はこう教えてくれます。あなたは不均衡や不公正に直面しているか、心のなかに後ろめたさがあって、胸を張れないのかもしれません。東洋の智慧は「瓜を種うれば瓜を得、豆を種うれば豆を得る」と説きます——天を恨んだり人を責めたりするより、自分自身の因果を振り返ってみてください。自分の選択と責任に正直に向き合い、偏りを正し、心を中正平和の位置に戻してください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (12, '吊るされた男', 'upright', '吊るされた男は、「逆さまこそ道の働き」の深い意味のような存在です——一見停滞していても、実は退いて進んでいる。一見犠牲に見えても、実は新しい視野を得ているのです。あなたは今、執着を手放し、視点を転換する必要のある時を迎えています。道家は「曲がるからこそ完全であり、曲がるからこそ直くなる」と説きます。時には世界を逆さまに見ることで、初めて真実が見えてくるのです。今の「吊るされている」状態は必要な静定であり、エネルギーが再び流れ出すためのものなのです。', 'ja'),
  (12, '吊るされた男', 'reversed', '逆位の吊るされた男はこう教えてくれます。あなたはただ無駄に苦しんでいて、苦境から何の気づきも得られていないかもしれません。あるいは、必要な手放しを拒み、古いやり方で進み続けようとしているかもしれません。東洋の智慧は「捨てるからこそ得られる」と説きます。あなたが今、固く握りしめているものは何ですか？その執着はすでにあなたの枷になっていませんか？手を放そうと決めたその瞬間こそ、転機の始まりなのです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (13, '死神', 'upright', '死神は、東洋の智慧において終わりではなく、「生々として息まざる」変容です——四季が巡り草木が枯れては萌えるように、古い形が消えゆくのは、新しい生命が到来するためなのです。あなたは今、深い変容の段階にあります。蛇が古い皮を脱ぐように、終わりは必要なのです。道家は「ただ盈たないからこそ、古くして新たに成ることができる」と説きます。古い自分を手放してこそ、新しい生へと向かうことができるのです。', 'ja'),
  (13, '死神', 'reversed', '逆位の死神はこう教えてくれます。あなたは必要な終わりに抗い、すでに枯れてしまった人や物に固執し続け、生命のエネルギーを滞らせているのかもしれません。易経「革卦」が示すように、天の時と人の心に従った変革は避けられません。東洋の智慧は「窮まれば則ち変じ、変ずれば則ち通ず」と説きます。どうか勇気を持って一つの段階の完了を受け入れてください。過去から解き放たれてこそ、新しい可能性が流れ込んでくるのです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (14, '節制', 'upright', '節制は、東洋の智慧における「中道」を体現しています——偏らず、ちょうど良い。あなたは今、調和と均衡が求められる段階にあります。易経「既済卦」の円満のように、太極図のなかで陰陽が完璧に溶け合うように。道家は「足るを知れば辱められず、止まるを知れば危うからず」と説きます。今は中庸の道で事にあたり、対立する力を互いに調和させてください。水が万物を潤すように、柔らかく、そして永く続くように。', 'ja'),
  (14, '節制', 'reversed', '逆位の節制はこう教えてくれます。あなたは不均衡な状態にあるのかもしれません——過ぎるか、足りないか。人生の調和を失っているのです。東洋の智慧は「過ぎたるはなお及ばざるがごとし」と説きます。今必要なのは、自分のリズムと配分を再調整することです。生活のどの側面のバランスが崩れているか（仕事と休息、与えることと受け取ること、理性と感情）を見つめ、中道に立ち返り、エネルギーが再び流れるようにしてください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (15, '悪魔', 'upright', '悪魔は、東洋の智慧では「心魔」のようなものです——執念・貪欲・無明による束縛。あなたは今、何か強い欲望や習慣に縛られています。しかしその束縛の鎖は、実はあなた自身が手放すことができるものなのです。道家は「五色は人の目を盲にし、五音は人の耳を聾にする」と説きます。気づくことこそが解脱の始まりです。執念の本質を見抜いたなら、あなたはすでに自由への道を歩んでいます。', 'ja'),
  (15, '悪魔', 'reversed', '逆位の悪魔は解脱の兆しです——あなたは束縛から抜け出し、人生の主導権を再び取り戻しつつあります。禅宗の「狂った心がふと止まれば、それ即ち菩提」のように、枷がただの虚ろな投影であると気づいたとき、それは崩れ始めます。今こそ断固として執念の鎖を断ち切ってください。ただし、自分自身にも優しく接してください。成長の過程には慈しみが必要なのです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (16, '塔', 'upright', '塔は、易経「震卦」の雷霆のようなものです——突然の震動が、偽りの安定を打ち砕きます。あなたは今、破壊的な出来事を経験しています。一見破滅に見えますが、実は虚ろな構造に終止符を打つものなのです。道家は「つむじ風は一晩中吹き続けず、にわか雨は一日中降り続けない」と説きます。激しい変化のあとには必ず静けさが戻ってきます。この過程を信じてください。打ち落とされたものは、もはや真実でない部分だけ。本当のあなたは、廃墟のなかから生まれ変わります。', 'ja'),
  (16, '塔', 'reversed', '逆位の塔はこう教えてくれます。あなたは必要な崩壊を必死に避けているか、災難の衝撃が過ぎ去り、その余波のなかで立て直している最中かもしれません。東洋の智慧は「禍いこそ福の寄りかかるところ」と説きます。災難に見える出来事のなかに、しばしば転機が隠れています。もう、ぐらつく古い構造を修繕しようとしないでください。必要な瓦解を許し、より真実で、より確固たる土台が築かれることを許してください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (17, '星', 'upright', '星は、東洋の夜空における「北辰（北極星）」の導きのようなものです——混沌と闇のあとに、希望の光が再び昇ってきます。あなたは今、癒しと再生の段階にあり、内なる憧れは星の光のように純粋で明るいものです。道家は「上善は水のごとし」と説きます。今は優しさと信頼をもって未来に向き合い、宇宙の善意を信じてください。希望の光があなたを迷いのなかから導き、清明へと向かわせてくれます。', 'ja'),
  (17, '星', 'reversed', '逆位の星はこう教えてくれます。あなたは希望が薄いと感じているか、未来への信頼を失い、内なる光が雲に覆われているのかもしれません。東洋の智慧は「天の運行は健やかであり、君子は自ら強くして休まない」と説きます——最も深い闇夜であっても、星は存在しています。どうか内なる信念を手放さないでください。まずは小さなことのなかから希望を取り戻し、その一点の星の光で、あなたの旅路を再び照らし出してください。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (18, '月', 'upright', '月は、東洋の智慧における「陰」の神秘のようなものです——潜在意識・幻影・まだ明らかにならない領域。あなたは今、はっきりとしない段階にあり、目の前のものは表面に見える通りではないかもしれません。道家は「おぼろげで捉えがたい、しかしそのなかには象がある」と説きます。月の下では、真実はまだ隠れています。今は軽々しく判断しないでください。直感を信じつつも、意識を保ち続けてください。雲が晴れ月が明らかになる日を待って、そのとき決断すればいいのです。', 'ja'),
  (18, '月', 'reversed', '逆位の月は霧が晴れる兆しです——あなたは幻影と恐れのなかから抜け出しつつあり、真実が少しずつ顕れてきています。易経「明夷」の卦の「艱難にあっても正しさを守れば利あり」のように、暗夜は尽き、黎明が近づいています。どうか意識を持ち続けてください。かつてあなたを怖がらせたものも、よく見ればそれほど恐ろしいものではないと分かるはずです。内なる迷いを抜けたとき、あなたはより深い清明を得ているのです。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (19, '太陽', 'upright', '太陽は「陽」の極致の輝きのようなものです——万物が明らかに照らされ、生気が満ちあふれています。あなたは今、光明に満ちた豊かな時期にあり、エネルギーが漲り、行うことはすべて形となって現れます。道家の「陽明」の道のように、今は心を開き、人生の美しさと温かさを存分に味わってください。同時に、その光で他者も照らしてください。この上向きのエネルギーに身を任せ、自然に開花させてください。', 'ja'),
  (19, '太陽', 'reversed', '逆位の太陽はこう教えてくれます。光が一時的に遮られているか、あなたが過度に誇張して内なるバランスを見失っているのかもしれません。東洋の智慧は「のぼりつめた龍には悔いがある」と説きます——陽が極まれば陰が生じる。過剰な光は自分自身を焦がすこともあります。喜びのなかでも謙虚さを保ち、成果のなかでも内なる静けさへ立ち返ることを忘れないでください。太陽の光が他者を温めると同時に、自分自身をも照らしますように。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (20, '審判', 'upright', '審判は、易経「復卦」の「一つの陽が戻ってくる」のようなものです——覚醒と再生の呼びかけ。あなたは今、深い内なる呼びかけに直面しています。過去の経験がこのとき再び見つめ直され、統合され、新たな意味を得ます。道家は「本源に立ち返る」と説きます。これは本当の自分と再会するときなのです。どうか内なる呼びかけに耳を傾け、過去を許し、再生を迎え入れてください。人生は新しい章へと進みます。', 'ja'),
  (20, '審判', 'reversed', '逆位の審判はこう教えてくれます。あなたは内なる呼びかけに抗っているか、自分自身や他者を許せず、過去を前進の荷物にしているのかもしれません。東洋の智慧は「包丁を置けば、その場で仏になれる」と説きます——悟りはただ今この一瞬の思いにあります。どうか自己批判をやめ、やり直すことを自分に許してください。内なる声に正直に向き合おうとしたその瞬間、あなたはすでに再生の道を歩んでいます。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (21, '世界', 'upright', '世界は、易経「既済」のあとの円満のようなもの、また太極の完成のようなものです——ひとつの循環の完遂。あなたは今、一つの段階の完成と統合を迎え、これまでの努力がこのとき花開き実を結びます。道家は「功成りて身退く」と説きます。円満のあとは停滞ではなく、新しい循環への備えなのです。まずこの達成と円満を余すところなく味わい尽くしてください。そして澄んだ心で、次の旅を始めてください。', 'ja'),
  (21, '世界', 'reversed', '逆位の世界はこう教えてくれます。あなたは円満に近づきながらも、どうしても完成させられないか、やってくる「完成」に不安を感じているのかもしれません。東洋の智慧は「物は極まれば必ず反り、周りて復す」と説きます——円満は終点ではなく、次の循環の始まりなのです。何があなたを最後の一歩でためらわせているのかを見つめ、「完璧」への執着を手放し、勇気を持ってゴールラインを越えてください。新しい始まりを迎えるために。', 'ja');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (0, '바보', 'upright', '역경 ''건괘'' 초구의 잠룡처럼, 당신은 지금 완전히 새로운 출발점에 서 있어요. 순수한 믿음과 무한한 가능성을 안고 말이죠. 동양의 지혜가 말해줘요: 진정한 도는 알지 못함에서 시작해 비로소 아는 것이에요. 지금은 지나치게 계획할 필요 없이, 내면의 직감을 따라 앞으로 나아가세요. 모험처럼 보이는 발걸음 하나하나가 모두 깨달음으로 가는 길이에요. 결과에 대한 집착을 내려놓고 지금 이 순간의 경험을 즐기세요. 그 천진함이 바로 당신의 가장 소중한 힘이랍니다.', 'ko'),
  (0, '바보', 'reversed', '역방향 바보는 이렇게 알려줘요: 지나친 무모함 때문에 도에서 벗어났을 수도 있고, 미지에 대한 두려움 때문에 계속 제자리걸음을 하고 있을 수도 있어요. 동양의 지혜는 ''그칠 줄 알아야 비로소 안정이 온다''고 말해요. 지금 필요한 것은 질주가 아니라 수렴이에요. 잠시 발걸음을 멈추고 자신의 충동이 어디에서 오는지 관찰한 다음, 방향을 다시 맞추고 맑은 마음으로 다음 발걸음을 내딛으세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (1, '마술사', 'upright', '마술사는 동양의 지혜에서 ''태극이 음양을 낳는'' 창조의 힘과 같아요. 당신의 손에는 이미 천지의 기운이 쥐어져 있고, 만사가 준비되어 있어요. 도가는 ''무위이위''를 말해요. 의도와 행동, 자원이 셋이 하나가 되면 창조는 자연스럽게 일어나요. 지금이야말로 내면의 지혜를 바깥의 현실로 옮길 때예요. 자신의 능력을 믿고 에너지가 순리에 따라 흐르게 두세요. 모든 것이 이루어질 수 있어요.', 'ko'),
  (1, '마술사', 'reversed', '역방향 마술사는 이렇게 알려줘요: 에너지가 제대로 통하지 않거나 의도가 순수하지 않아 창조가 막혀 있어요. 역경 ''몽괘''가 보여주듯, 먼저 마음을 바로 세우는 계몽이 있어야 비로소 통할 수 있어요. 자신의 동기와 방법을 살펴보세요. 지나치게 조종하려 하거나, 성급하게 결과만 바라보고 있지는 않은지요. ''허함의 극치에 이르고 고요함을 굳게 지키는'' 상태로 돌아가, 기술에 집착하는 대신 내면의 지혜가 다시 주도하도록 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (2, '여사제', 'upright', '여사제는 도가에서 말하는 ''고요한 관조''의 도와 같아요. 당신은 지금 내면이 고요하고 직감이 트인 상태에 있어요. 동양의 지혜는 ''허함의 극치에 이르고 고요함을 굳게 지켜라''고 말해요. 만물이 함께 움직여도 나는 그 회귀를 관찰하라고요. 지금은 바깥에서 답을 찾을 필요가 없어요. 답은 이미 당신 마음속에 있어요. 조용히 앉아 명상하고, 내면의 아주 작은 소리에 귀 기울이세요. 아직 드러나지 않은 그 지혜가 고요함 속에서 당신을 만나기를 기다리고 있답니다.', 'ko'),
  (2, '여사제', 'reversed', '역방향 여사제는 이렇게 알려줘요: 당신은 내면의 직감과 연결이 끊어져 있고, 바깥의 시끄러움에 마음의 소리가 묻혀 있을지도 몰라요. 역경 ''감괘''의 험한 함정처럼, 마음의 호수가 출렁이면 비추는 상도 왜곡되기 마련이에요. 다시 고요한 공간을 찾으세요. 지나친 생각과 걱정을 내려놓고 마음을 거울처럼 맑게 되돌리면, 진실한 감각이 다시 떠오를 거예요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (3, '여황제', 'upright', '여황제는 동양의 지혜 중 ''후덕재물''을 보여줘요. 대지의 어머니 같은 풍요와 자양이에요. 당신은 지금 수확과 성장의 계절에 있어요. 곤괘가 말하는 ''땅의 형세는 곤하니, 군자는 두터운 덕으로 만물을 실어 나른다''처럼요. 지금은 삶이 주는 선물을 활짝 열고 받아들이고, 눈앞의 풍요를 즐기면서 그 풍요로 주변 사람들도 자양하세요. 자연의 리듬에 몸을 맡기면 생명이 꽃처럼 활짝 피어날 거예요.', 'ko'),
  (3, '여황제', 'reversed', '역방향 여황제는 이렇게 알려줘요: 당신은 자양의 근원과 단절되어 있거나, 지나치게 베풀다가 정작 자신의 필요는 돌보지 않고 있을지도 몰라요. 땅이 비를 잃은 것처럼 생명이 메마르기 시작했어요. 먼저 자신을 돌보세요. 몸과 감정, 마음의 필요를요. 자신이 충만해야 진정으로 베풀 수 있으니까요. 자연의 품으로 돌아가 조건 없는 사랑과 자양을 다시 연결하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (4, '황제', 'upright', '황제는 동양의 지혜에서 ''강건하고 바르며 중도에 선'' 리더십을 상징해요. 건괘가 말하는 ''스스로 힘써 쉬지 않는다''처럼요. 당신은 지금 질서를 세우고 구조를 확립할 때에 있어요. 당신의 결단과 원칙이 상황에 안정감을 더해 주고 있어요. 도가는 무위를 말하지만, 구조가 필요한 곳에서는 명확한 경계와 규율이 바로 ''도''의 드러남이에요. 공정함과 안정으로 앞을 이끌어 가세요.', 'ko'),
  (4, '황제', 'reversed', '역방향 황제는 이렇게 알려줘요: 지나친 통제나 굳어진 규칙이 오히려 자신을 가두는 올가미가 되고 있어요. 역경 ''쾌괘''가 보여주듯, 고집스러운 자만은 결국 손해를 부르게 돼요. 동양의 지혜는 ''부드러움이 강함을 이긴다''고 말해요. 지금 필요한 것은 집착을 내려놓고 변통과 융통성을 허용하는 거예요. 진정한 힘은 꽉 쥐는 데 있는 게 아니라, 굽혔다 펼 수 있는 지혜에 있어요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (5, '교황', 'upright', '교황은 동양의 ''스승의 도''와 같아요. 당신은 지금 전승과 배움의 단계에 있고, 전통의 지혜가 앞길을 밝혀 주고 있어요. 도가는 ''도는 자연을 본받는다''고 말하지만, 도로 가는 길에서 좋은 스승의 인도는 더없이 소중해요. 지금은 겸허히 가르침을 청하고, 오랜 시간 검증된 법칙을 따르면서도 ''책을 다 믿는 것은 책이 없는 것만 못하다''는 말을 잊지 마세요. 전승 속에서도 자신만의 체득의 공간을 지켜야 해요.', 'ko'),
  (5, '교황', 'reversed', '역방향 교황은 이렇게 알려줘요: 당신은 기존의 틀에 지나치게 기대고 있거나, 권위의 교리에 의문을 품기 시작했을지도 몰라요. 선종의 ''문자를 세우지 않고 마음을 직접 가리킨다''는 정신처럼, 진정한 도는 형식이 아니라 당신의 직접적인 체험 속에 있어요. 내면의 목소리를 듣고 굳어진 교리를 넘어서 자신만의 길을 찾으세요. 다만 전통의 가치까지 완전히 부정할 필요는 없어요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (6, '연인', 'upright', '연인은 동양의 지혜에서 ''음양이 화합하는'' 도와 같아요. 대립하는 힘이 지금 이 순간 원만한 융합을 이루고 있어요. 당신은 지금 중요한 선택 앞에 서 있고, 그 선택의 핵심은 ''하나 됨''이에요. 내면의 가치와의 일치, 타인과의 조화로운 공명이요. 도가는 ''만물은 음을 업고 양을 안는다''고 말해요. 진정한 조화는 차이를 없애는 게 아니라 서로 다른 힘이 서로를 완성하게 하는 거예요.', 'ko'),
  (6, '연인', 'reversed', '역방향 연인은 이렇게 알려줘요: 내면의 가치관이 충돌하고 있고, 선택의 양쪽 끝이 당신을 갈기갈기 찢고 있어요. 역경 ''규괘''가 보여주듯, 이반과 대립 속에서 새로운 균형을 찾아야 해요. 먼저 마음의 중심으로 돌아가 무엇이 당신에게 진정으로 중요한지 정리하세요. 모순 속에서 통일의 가능성을 찾고, 갈라진 에너지가 다시 화해하도록 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (7, '전차', 'upright', '전차는 동양의 지혜 중 ''다스림의 도''를 보여줘요. 역경 ''사괘''의 무리를 다스리는 지혜처럼, 바름으로 세력을 다스리고 고요함으로 움직임을 제어하는 거예요. 당신은 지금 굳은 의지와 방향 잡기가 필요한 때에 있어요. 앞길에 도전이 있더라도 목표가 명확하고 마음이 한곳에 집중되어 있으면, 수레를 몰듯 안정적으로 나아갈 수 있어요. 부드러움으로 강함을 다스리고, 안정으로 변화에 대응하세요.', 'ko'),
  (7, '전차', 'reversed', '역방향 전차는 이렇게 알려줘요: 당신은 방향을 잃었거나 내면의 모순에 갇혀 에너지가 흩어지고, 나아갈 수도 물러설 수도 없는 상태일지도 몰라요. 동양의 지혜는 ''그칠 줄 알면 위태롭지 않다''고 말해요. 어디로 가야 할지 모를 때, 멈추는 것도 나아가는 방법 중 하나예요. 먼저 내면의 갈등을 정리하고 목표를 다시 세워, 의지와 행동이 다시 하나가 되게 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (8, '힘', 'upright', '힘은 동양의 지혜에서 대결이 아니라 ''부드러움으로 강함을 이기는'' 길들이기의 도예요. 도가가 호랑이를 다루듯 완력이 아니라 내면의 고요한 안정으로 다루는 것이죠. 당신은 지금 진정한 용기를 보여주고 있어요. 마음속 맹수, 곧 두려움과 욕망, 충동을 마주할 때 억누르거나 맞서 싸우는 게 아니라 다정하게 받아들이고 인도하는 거예요. 그 내면의 평화야말로 가장 강력한 힘이에요.', 'ko'),
  (8, '힘', 'reversed', '역방향 힘은 이렇게 알려줘요: 당신은 지금 내면의 어떤 힘과 사투를 벌이고 있거나, 자신에 대한 믿음을 잃고 있을지도 몰라요. 동양의 지혜는 ''부드러움이 강함을 이긴다''고 말해요. 정면으로 부딪히면 자신만 소모될 뿐이에요. 대결을 멈추고 자신의 두려움과 약함을 자비로운 시선으로 바라보세요. 수용 속에서 그 다정하면서도 단단한 힘을 다시 찾을 수 있을 거예요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (9, '은자', 'upright', '은자는 동양의 ''은둔자''와 같아요. 당신은 지금 홀로 있음과 내면 성찰의 단계에 있고, 이는 지혜로 가는 필수적인 길이에요. 도가는 ''배움을 위해서는 날마다 더하고, 도를 위해서는 날마다 덜어낸다''고 말해요. 지금의 독자적인 시간은 도피가 아니라, 바깥의 허식을 벗겨내고 내면의 진실로 돌아가는 거예요. 등불을 들고 홀로 걷는 것은 자신을 비추기 위해서이자, 자신의 진짜 길을 또렷이 보기 위해서예요.', 'ko'),
  (9, '은자', 'reversed', '역방향 은자는 이렇게 알려줘요: 당신은 지나치게 폐쇄되어 있거나 내면의 고독을 마주하기를 거부해서, 혼자 있음이 고립으로 변했을지도 몰라요. 동양의 지혜는 ''빛을 부드럽게 하고 먼지와 함께한다''고 말해요. 진정한 수행자는 세상을 떠나지 않고, 속세 속에서도 마음의 맑음을 지켜요. 혼자 있음과 연결 사이의 균형을 찾으세요. 내면 성찰이 도피의 구실이 아니라 행동의 지혜로 이어지도록요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (10, '운명의 수레바퀴', 'upright', '운명의 수레바퀴는 동양의 지혜에서 ''음양의 성쇠와 하늘의 순환''과 같아요. 만물은 각자의 때가 있고, 극에 달하면 쇠하고 궁하면 다시 통해요. 당신은 지금 자연스러운 전환점에 있고, 일어나는 모든 일에는 깊은 뜻이 있어요. 도가는 ''자연에 순응하라''고 말해요. 지금 가장 좋은 태도는 변화를 거부하는 것이 아니라 하늘의 도에 몸을 맡기고, 수레바퀴가 도는 가운데서도 마음의 안정을 지키는 거예요. 어쩔 수 없는 일은 운명으로 받아들이고 편안히 사는 것이죠.', 'ko'),
  (10, '운명의 수레바퀴', 'reversed', '역방향 운명의 수레바퀴는 이렇게 알려줘요: 당신은 운이 좋지 않다고 느끼거나, 삶에서 거부할 수 없는 변화를 거부하고 있을지도 몰라요. 역경 ''박괘''가 보여주듯, 음이 자라고 양이 쇠하는 때일수록 바름을 지키며 때를 기다려야 해요. 동양의 지혜는 ''새옹지마''라고 말해요. 지금의 역전이 어쩌면 전환의 시작일지도 몰라요. 인내와 믿음을 지키며 순환에 순응하고, 때가 오기를 기다리세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (11, '정의', 'upright', '정의는 동양의 지혜에서 ''하늘의 도는 친함이 없고 항상 착한 사람과 함께한다''는 말과 같아요. 인과는 있는 그대로 실현되어 조금도 어긋나지 않아요. 당신은 지금 공정한 판단이 필요한 순간을 마주하고 있고, 그 판단은 마음의 맑음과 양심에서 나와야 해요. 도가는 ''무위이치''를 말해요. 진정한 공의는 사람이 만든 재단이 아니라 자연의 법칙에 순응한 결과예요. 공정한 마음으로 행하고 양심에 부끄럽지 않으면, 그 자체가 탄탄대로예요.', 'ko'),
  (11, '정의', 'reversed', '역방향 정의는 이렇게 알려줘요: 당신은 지금 불균형이나 불공정을 마주하고 있거나, 마음속에 빚진 것이 있어 떳떳하지 못할지도 몰라요. 동양의 지혜는 ''콩 심은 데 콩 나고 팥 심은 데 팥 난다''고 말해요. 하늘을 원망하기보다 자신의 인과 속으로 돌아가 살펴보세요. 자신의 선택과 책임을 솔직하게 마주하고, 어긋난 곳을 바로잡아 마음이 바르고 평온한 자리로 돌아오게 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (12, '매달린 사람', 'upright', '매달린 사람은 ''도는 반대로 움직인다''는 깊은 뜻과 같아요. 멈춘 것 같지만 실은 물러서서 나아가는 것이고, 희생하는 것 같지만 실은 새로운 시야를 얻는 거예요. 당신은 지금 집착을 내려놓고 시야를 전환해야 할 때에 있어요. 도가는 ''굽으면 온전하고, 휘면 곧아진다''고 말해요. 때로는 세상을 거꾸로 보아야 진실이 보여요. 지금의 ''매달림''은 필요한 고요함이며, 에너지가 다시 흐르게 하는 과정이에요.', 'ko'),
  (12, '매달린 사람', 'reversed', '역방향 매달린 사람은 이렇게 알려줘요: 당신은 그저 헛되이 고생만 하고 어려움에서 아무런 깨달음도 얻지 못하고 있을지도 몰라요. 아니면 필요한 내려놓음을 거부하고 옛 방식으로만 나아가려 하고 있을지도요. 동양의 지혜는 ''버려야 얻는다''고 말해요. 버림이 있어야 얻음이 있어요. 당신이 꽉 붙잡고 있는 것이 무엇인지 살펴보세요. 그 집착이 이미 당신의 족쇄가 되지는 않았는지요. 놓기로 마음먹는 그 순간이 바로 전환의 시작이에요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (13, '죽음', 'upright', '죽음은 동양의 지혜에서 끝이 아니라 ''끊임없이 살아 움직이는'' 변신이에요. 사계절이 돌고 초목이 시들었다 무성해지듯, 옛 형태가 사라지는 것은 바로 새 생명이 오기 위함이에요. 당신은 지금 깊은 전환의 단계에 있고, 끝맺음은 필요해요. 뱀이 묵은 껍질을 벗는 것처럼요. 도가는 ''가득 차 있지 않아야 낡은 것을 덮고 새것을 이룬다''고 말해요. 옛 나를 내려놓아야 새 삶을 맞이할 수 있어요.', 'ko'),
  (13, '죽음', 'reversed', '역방향 죽음은 이렇게 알려줘요: 당신은 필요한 끝맺음을 거부하고, 이미 시들어 버린 사람이나 일을 붙잡고 있어서 생명의 에너지가 정체되고 있을지도 몰라요. 역경 ''혁괘''가 보여주듯, 하늘과 사람의 뜻에 따르는 변혁은 피할 수 없어요. 동양의 지혜는 ''궁하면 변하고, 변하면 통한다''고 말해요. 용기 있게 한 단계의 완성을 받아들이고 과거에서 벗어나면, 새로운 가능성이 흘러들어올 거예요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (14, '절제', 'upright', '절제는 동양의 지혜 중 ''중도''를 보여줘요. 치우치지도 않고 지나치지도 않은, 꼭 알맞음이에요. 당신은 지금 조화와 균형이 필요한 단계에 있어요. 역경 ''기제괘''의 원만함처럼, 태극 그림 속 음양의 완벽한 어울림처럼요. 도가는 ''만족할 줄 알면 욕되지 않고, 그칠 줄 알면 위태롭지 않다''고 말해요. 지금은 중용의 도로 행하고, 대립하는 힘이 서로 조화를 이루게 하세요. 물이 만물을 적시듯 부드럽고 오래 가는 방식으로요.', 'ko'),
  (14, '절제', 'reversed', '역방향 절제는 이렇게 알려줘요: 당신은 지금 불균형한 상태에 있을지도 몰라요. 지나치거나 모자라서 삶의 조화를 잃고 있죠. 동양의 지혜는 ''지나침은 모자람만 못하다''고 말해요. 지금 필요한 것은 당신의 리듬과 비율을 다시 맞추는 거예요. 삶의 어느 면이 균형을 잃었는지 살펴보세요. 일과 휴식, 주고받기, 이성과 감정처럼요. 중도로 돌아가 에너지가 다시 흐르게 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (15, '악마', 'upright', '악마는 동양의 지혜에서 ''심마''와 같아요. 집착, 탐욕, 무명의 속박이에요. 당신은 지금 어떤 강렬한 욕망이나 습관에 묶여 있고, 그 족쇄는 사실 당신 스스로 풀 수 있는 것이에요. 도가는 ''다섯 가지 색이 사람의 눈을 멀게 하고, 다섯 가지 소리가 사람의 귀를 멀게 한다''고 말해요. 알아차림이 바로 해탈의 시작이에요. 집착의 본질을 꿰뚫어 보면, 당신은 이미 자유의 길 위에 서 있는 거예요.', 'ko'),
  (15, '악마', 'reversed', '역방향 악마는 해탈의 징조예요. 당신은 지금 속박에서 벗어나 삶의 주도권을 다시 찾고 있어요. 선종의 ''미친 마음이 문득 그치면, 그침이 곧 보리''라는 말처럼, 족쇄가 허상의 투영에 불과하다는 걸 알아차리는 순간 그것은 무너지기 시작해요. 지금은 집착의 사슬을 단호하게 끊으면서도 자신을 다정하게 바라보세요. 성장의 과정에는 자비가 필요하니까요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (16, '탑', 'upright', '탑은 역경 ''진괘''의 천둥과 같아요. 갑작스러운 진동이 거짓된 견고함을 깨뜨려요. 당신은 지금 한바탕 뒤집힘을 겪고 있고, 겉보기엔 파괴 같지만 실은 허상의 구조에 마침표를 찍는 거예요. 도가는 ''돌풍은 아침 내내 불지 않고, 폭우는 하루 종일 내리지 않는다''고 말해요. 격변 뒤에는 반드시 고요가 찾아와요. 이 과정을 믿으세요. 무너져 내린 것은 더 이상 진실하지 않은 부분이고, 진짜 당신은 폐허 속에서 다시 태어날 거예요.', 'ko'),
  (16, '탑', 'reversed', '역방향 탑은 이렇게 알려줘요: 당신은 필요한 붕괴를 애써 피하고 있거나, 재난의 충격이 지나간 뒤 그 여파 속에서 다시 정비하고 있을지도 몰라요. 동양의 지혜는 ''화가 복에 기대어 있다''고 말해요. 재난처럼 보이는 변고 속에 전환이 숨어 있는 경우가 많아요. 흔들리는 옛 구조를 더 이상 수리하려 하지 마세요. 필요한 해체를 허용해야 더 진실하고 더 단단한 기초가 세워질 수 있어요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (17, '별', 'upright', '별은 동양의 밤하늘에서 ''북극성''의 인도와 같아요. 혼돈과 어둠이 지난 뒤, 희망의 빛이 다시 떠올라요. 당신은 지금 치유와 재생의 단계에 있고, 마음속 갈망이 별빛처럼 순수하고 밝게 빛나고 있어요. 도가는 ''가장 높은 선은 물과 같다''고 말해요. 지금은 부드러움과 믿음으로 미래를 마주하세요. 우주의 선의를 믿고, 희망의 빛이 당신을 안내해 미혹을 지나 맑음으로 향하게 하세요.', 'ko'),
  (17, '별', 'reversed', '역방향 별은 이렇게 알려줘요: 당신은 희망이 희미하다고 느끼거나 미래에 대한 믿음을 잃고, 마음속 빛이 구름에 가려져 있을지도 몰라요. 동양의 지혜는 ''하늘의 운행은 강건하니, 군자는 스스로 힘써 쉬지 않는다''고 말해요. 가장 깊은 밤에도 별은 존재해요. 내면의 믿음을 버리지 마세요. 아주 작은 일에서부터 희망을 다시 찾고, 그 별빛이 당신의 여정을 다시 밝히게 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (18, '달', 'upright', '달은 동양의 지혜 중 ''음''의 신비와 같아요. 무의식, 환상, 아직 밝혀지지 않은 경지예요. 당신은 지금 흐릿하고 불명확한 단계에 있고, 눈앞의 사물은 보이는 그대로가 아닐 수 있어요. 도가는 ''아득하고 어렴풋하지만 그 속에 형상이 있다''고 말해요. 달빛 아래, 진실은 아직 드러나지 않았어요. 지금은 함부로 판단을 내리지 마세요. 직감을 믿되 경계심도 유지하고, 구름이 걷히고 달이 밝아지는 날을 기다렸다가 결정을 내리세요.', 'ko'),
  (18, '달', 'reversed', '역방향 달은 안개가 걷히는 징조예요. 당신은 지금 환상과 두려움에서 걸어 나오고 있고, 진실이 점차 드러나고 있어요. 역경 ''명이괘''의 ''어려운 때일수록 바름을 지키면 이롭다''는 말처럼, 어두운 밤이 끝나가고 새벽이 다가오고 있어요. 계속 경계심을 유지하세요. 당신을 두렵게 했던 것들은 자세히 들여다보면 사실 그렇게 무섭지 않은 경우가 많아요. 내면의 미혹을 지나오면 더 깊은 맑음을 얻게 될 거예요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (19, '태양', 'upright', '태양은 ''양''의 극치의 광휘와 같아요. 만물이 또렷이 드러나고 생기가 가득해요. 당신은 지금 밝고 풍요로운 시기에 있고, 에너지가 충만해서 하는 일마다 결실을 맺어요. 도가는 ''양명''의 도를 말해요. 지금은 마음을 활짝 열고 삶의 아름다움과 따뜻함을 마음껏 누리면서, 그 빛으로 다른 사람들도 비추어 주세요. 이 위로 향하는 에너지에 몸을 맡기고 자연스럽게 꽃피우게 하세요.', 'ko'),
  (19, '태양', 'reversed', '역방향 태양은 이렇게 알려줘요: 빛이 잠시 가려져 있을 수도 있고, 당신이 지나치게 뽐내며 내면의 균형을 놓치고 있을 수도 있어요. 동양의 지혜는 ''항룡유회''라고 말해요. 하늘 높이 오른 용은 뉘우침이 있다는 뜻이죠. 양이 극에 달하면 음이 생기듯, 지나친 빛은 자신을 태울 수도 있어요. 기쁨 속에서도 겸손을 지키고, 성취 속에서도 내면의 고요로 돌아오는 것을 잊지 마세요. 태양빛이 남을 따뜻하게 하듯 자신도 비추게 하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (20, '심판', 'upright', '심판은 역경 ''복괘''의 ''한 줄기 양기가 돌아온다''와 같아요. 각성과 재생의 부름이에요. 당신은 지금 깊은 내면의 부름을 마주하고 있고, 과거의 경험이 이 순간 다시 살펴지고 통합되며 새로운 의미를 얻어요. 도가는 ''근본으로 돌아가 원천으로 되돌아간다''고 말해요. 이것은 진짜 나와 다시 만나는 순간이에요. 내면의 부름을 듣고 과거를 용서하며 재생을 맞이하세요. 삶이 새로운 장으로 들어서게요.', 'ko'),
  (20, '심판', 'reversed', '역방향 심판은 이렇게 알려줘요: 당신은 내면의 부름을 거부하고 있거나, 자신과 타인을 용서하지 못해 과거가 앞으로 나아가는 짐이 되고 있을지도 몰라요. 동양의 지혜는 ''칼을 내려놓으면 그 자리에서 부처가 된다''고 말해요. 깨달음은 오직 지금 이 순간의 한 생각에 있어요. 자기 비난을 멈추고, 자신이 다시 시작할 수 있게 허락하세요. 내면의 목소리를 솔직하게 마주하려는 순간, 당신은 이미 재생의 길 위에 서 있는 거예요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (21, '세계', 'upright', '세계는 역경 ''기제'' 이후의 원만함과 같고, 태극의 완성과도 같아요. 하나의 순환이 완전히 마무리되는 것이에요. 당신은 지금 한 단계의 완성과 통합의 시점에 있고, 지난 노력이 이 순간 꽃을 피워 결실을 맺어요. 도가는 ''공을 이루면 물러나라''고 말해요. 원만함 이후는 정체가 아니라 새로운 순환을 맞을 준비예요. 먼저 이 성취와 원만함을 온전히 경험한 다음, 맑은 마음으로 다음 여정을 시작하세요.', 'ko'),
  (21, '세계', 'reversed', '역방향 세계는 이렇게 알려줘요: 당신은 원만함에 거의 다다랐지만 끝내 완성하지 못하고 있거나, 다가올 ''완성''에 불안을 느끼고 있을지도 몰라요. 동양의 지혜는 ''물건은 극에 달하면 반하고, 돌고 돌아 다시 시작한다''고 말해요. 원만함은 끝이 아니라 다음 순환의 출발점이에요. 마지막 한 걸음에서 무엇이 당신을 망설이게 하는지 살펴보세요. ''완벽함''에 대한 집착을 내려놓고, 용기 있게 결승선을 넘어 새로운 시작을 맞이하세요.', 'ko');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (0, '愚者', 'upright', '如同易经「乾卦」初九的潜龙，你正站在一个全新的起点，带着纯粹的信任与无限可能。东方智慧告诉你：真正的道，始于无知而知。此刻不需过度计划，顺应内在的直觉前行，每一次看似冒险的脚步，都是通往觉醒的路。放下对结果的执着，享受当下的体验，这份天真正是你最珍贵的力量。', 'zh-CN'),
  (0, '愚者', 'reversed', '逆位的愚者提醒你：你可能因过度鲁莽而偏离了道，或是对未知的恐惧让你不断原地踏步。东方智慧讲究「知止而后有定」，此时需要的是收敛，而非横冲直撞。请先停下脚步，观照自己的冲动从何而来，重新校准方向，再以清明的心踏出下一步。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (1, '魔术师', 'upright', '魔术师在东方智慧中如同「太极生两仪」的创造之力——你手中已握有天地之气，万事俱备。道家讲「无为而为」，当你的意图、行动与资源三者合一，创造便自然发生。此刻正是将内在智慧化为外在实相的时刻，信任你的能力，让能量顺流而下，一切皆可成。', 'zh-CN'),
  (1, '魔术师', 'reversed', '逆位的魔术师提示你：能量未能贯通，或意图不纯，导致创造受阻。如同易经「蒙卦」所示，需先启蒙正心，方能通达。请检视你的动机与方法——是否过度操弄、急于求成？回到「致虚极，守静笃」的状态，让内在的智慧重新主导，而非执着于技巧。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (2, '女祭司', 'upright', '女祭司如同道家所说的「静观」之道——你正处于内在沉静、直觉通达的状态。东方智慧讲「致虚极，守静笃」，万物并作，吾以观复。此刻不需向外寻求答案，答案已在你心底。静坐、冥想、聆听内在的微声，那隐而未显的智慧，正等待你在宁静中与之相遇。', 'zh-CN'),
  (2, '女祭司', 'reversed', '逆位的女祭司提醒你：你可能与内在的直觉断了连结，被外在的喧嚣淹没了心声。如同易经「坎卦」的险陷，心湖波动则映照失真。请重新找回静默的空间，放下过度的思虑与担忧，让心回到如镜的状态，真实的感知便会重新浮现。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (3, '皇后', 'upright', '皇后体现了东方智慧中的「厚德载物」——大地之母的丰盛与滋养。你正处于丰收与成长的季节，如坤卦「地势坤，君子以厚德载物」。此时应敞开接纳生命给予的礼物，享受当下的丰饶，同时以这份丰盛去滋养身边的人。顺应自然的节奏，让生命如花般绽放。', 'zh-CN'),
  (3, '皇后', 'reversed', '逆位的皇后提醒你：你可能与滋养的源头脱节，过度付出而忽略了自己的需要。如同大地失去雨水，生命开始枯竭。请先照顾好自己——身体、情感与心灵的需求，唯有自身丰盈，才能真正的给予。回到自然的怀抱，重新连结那份无条件的爱与滋养。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (4, '皇帝', 'upright', '皇帝在东方智慧中象征「刚健中正」的领导之道，如乾卦所言的「自强不息」。你正处于建立秩序、确立结构的时刻，你的决断与原则为局面提供了安定的力量。道家虽讲无为，但在需要结构之处，明确的界限与规律正是「道」的显现。以公正与稳定引领前行。', 'zh-CN'),
  (4, '皇帝', 'reversed', '逆位的皇帝提醒你：过度的掌控或僵化的规则，反而成了束缚自己的牢笼。如同易经「夬卦」所示，刚愎自用终将招损。东方智慧讲「柔弱胜刚强」，此刻需要的是放下执念，容许变通与弹性。真正的力量不在于紧握，而在于能屈能伸的智慧。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (5, '教皇', 'upright', '教皇如同东方的「师道」——你正处于传承与学习的阶段，传统的智慧为你照亮前路。道家讲「道法自然」，而通往道的路上，善知识的引导弥足珍贵。此时应虚心求教，遵循经过时间验证的法则，同时不忘「尽信书不如无书」，在传承中保有自己的体悟空间。', 'zh-CN'),
  (5, '教皇', 'reversed', '逆位的教皇提醒你：你可能过度依附于既有的框架，或对权威的教条产生了怀疑。如同禅宗「不立文字，直指人心」的精神——真正的道不在形式，而在于你的亲身体证。请聆听内在的声音，突破僵化的教条，找到属于你自己的道路，但也不需完全否定传统的价值。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (6, '恋人', 'upright', '恋人在东方智慧中如同「阴阳和合」之道——对立的力量在此刻达成圆满的融合。你正面临一个重要的选择，而这个选择的关键在于「合一」：与内在价值的一致、与他人的和谐共鸣。道家讲「万物负阴而抱阳」，真正的和谐不是消除差异，而是让不同的力量相互成就。', 'zh-CN'),
  (6, '恋人', 'reversed', '逆位的恋人提醒你：内在的价值观正在冲突，选择的两端让你感到撕裂。如同易经「睽卦」所示，背离与对立之中，需要寻求新的平衡。请先回到内心的中心，厘清什么对你而言真正重要，在矛盾中寻找统一的可能，让分裂的能量重新和解。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (7, '战车', 'upright', '战车体现了东方智慧中的「驾驭之道」——如易经「师卦」的治众之术，以正御势，以静制动。你正处于需要坚定意志、掌控方向的时刻，前方的道路虽有挑战，但只要你目标明确、心志专一，便能如驭车般稳健前行。以柔驭刚，以定应变。', 'zh-CN'),
  (7, '战车', 'reversed', '逆位的战车提醒你：你可能失去了方向，或被内在的矛盾所困，导致能量涣散、进退失据。东方智慧讲「知止不殆」——当你不知该往何处时，停下也是前进的一种方式。请先安顿内在的冲突，重新确立目标，让意志与行动重新合而为一。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (8, '力量', 'upright', '力量在东方智慧中不是对抗，而是「以柔克刚」的驯服之道——如道家驭虎，不靠蛮力而靠内在的定静。你正展现着真正的勇气：面对内心的猛兽（恐惧、欲望、冲动），不是压抑或对抗，而是温柔地接纳与引导。这份内在的平和，正是最强大的力量。', 'zh-CN'),
  (8, '力量', 'reversed', '逆位的力量提醒你：你可能正与内在的某股力量搏斗，或对自己失去了信心。东方智慧讲「柔弱胜刚强」，硬碰硬只会耗损自己。请先停止对抗，转而以慈悲看待自己的恐惧与软弱，在接纳中重新找回那份温柔而坚定的力量。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (9, '隐士', 'upright', '隐士如同东方的「隐者」——你正处于独处与内省的阶段，这是通往智慧必经之路。道家讲「为学日益，为道日损」，此刻的独处并非逃避，而是剥去外在的浮华，回归内在的真实。提着灯独行，是为了照亮自己，也为了看清自己真正的道路。', 'zh-CN'),
  (9, '隐士', 'reversed', '逆位的隐士提醒你：你可能过度封闭，或拒绝面对内在的孤独，让独处变成了隔离。东方智慧讲「和光同尘」——真正的修行者不离世间，而是在红尘中保持内心的清明。请在独处与连结之间找到平衡，让内省转化为行动的智慧，而非逃避的借口。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (10, '命运之轮', 'upright', '命运之轮在东方智慧中如同「阴阳消长、天道循环」——万物皆有其时，盛极而衰，否极泰来。你正处于一个自然的转折点，一切的发生皆有其深意。道家讲「顺其自然」，此刻最好的态度不是抗拒变化，而是随顺天道，在轮转中保持内心的稳定，知其不可奈何而安之若命。', 'zh-CN'),
  (10, '命运之轮', 'reversed', '逆位的命运之轮提醒你：你可能正感到时运不济，或抗拒生命中不可抗拒的变化。如同易经「剥卦」所示，阴长阳消之际，更需守正待时。东方智慧讲「塞翁失马，焉知非福」——此刻的逆转或许正是转机的开端。请保持耐心与信心，顺应循环，等待时机的到来。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (11, '正义', 'upright', '正义在东方智慧中如同「天道无亲，常与善人」——因果如实，丝毫不爽。你正面临一个需要公正判断的时刻，而这份判断应源于内心的清明与良知。道家讲「无为而治」，真正的公义不是人为的裁量，而是顺应自然法则的结果。以公正之心行事，问心无愧便是坦途。', 'zh-CN'),
  (11, '正义', 'reversed', '逆位的正义提醒你：你可能正面对失衡或不公，或内心有所亏欠，难以坦然。东方智慧讲「种瓜得瓜，种豆得豆」——与其怨天尤人，不如回到自身的因果中检视。请诚实面对自己的选择与责任，修正失衡之处，让心回到中正平和的位置。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (12, '倒吊人', 'upright', '倒吊人如同「反者道之动」的深意——看似停滞，实则以退为进；看似牺牲，实则换得新的视野。你正处于一个需要放下执着、转换视角的时刻。道家讲「曲则全，枉则直」，有时倒过来看世界，才能看清真相。此刻的「悬挂」是必要的静定，让能量重新流动。', 'zh-CN'),
  (12, '倒吊人', 'reversed', '逆位的倒吊人提醒你：你可能只是白白受苦，未能从困境中获得领悟；或拒绝必要的放下，执意以旧方式前行。东方智慧讲「舍得」——有舍才有得。请检视你正紧抓不放的是什么，那份执着是否已成为你的枷锁？愿意松手的那一刻，正是转机的开始。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (13, '死亡', 'upright', '死亡在东方智慧中不是终结，而是「生生不息」的蜕变——如四季轮替、草木枯荣，旧的形态消逝，正是为了新生命的到来。你正处于一个深刻的转化阶段，结束是必要的，如同蛇蜕旧皮。道家讲「夫唯不盈，故能蔽而新成」，放下旧我，才能迎向新生。', 'zh-CN'),
  (13, '死亡', 'reversed', '逆位的死亡提醒你：你可能正抗拒必要的结束，紧抓着已经枯萎的人事物不放，导致生命能量停滞。如同易经「革卦」所示，顺天应人的变革不可避免。东方智慧讲「穷则变，变则通」，请勇敢地接受阶段的完成，让自己从过去中解脱，新的可能才会流入。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (14, '节制', 'upright', '节制体现了东方智慧中的「中道」——不偏不倚，恰到好处。你正处于一个需要调和与平衡的阶段，如同易经「既济卦」的圆满，也如同太极图中阴阳的完美交融。道家讲「知足不辱，知止不殆」，此时应以中庸之道行事，让对立的力量相互调和，如水之润物，柔和而持久。', 'zh-CN'),
  (14, '节制', 'reversed', '逆位的节制提醒你：你可能正处于失衡的状态——过度或不及，让生命失去和谐。东方智慧讲「过犹不及」，此刻需要的是重新校准你的节奏与比例。请检视生活的哪个面向失去了平衡（工作/休息、付出/接受、理性/情感），回归中道，让能量重新流动。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (15, '恶魔', 'upright', '恶魔在东方智慧中如同「心魔」——执念、贪欲与无明的束缚。你正被某种强烈的欲望或惯性所捆绑，而这束缚的锁链，其实是你可以放下的。道家讲「五色令人目盲，五音令人耳聋」，觉察即是解脱的开始。看清执念的本质，你便已走在自由的道路上。', 'zh-CN'),
  (15, '恶魔', 'reversed', '逆位的恶魔是解脱的征兆——你正在从束缚中挣脱，重新夺回生命的主导权。如同禅宗「狂心顿歇，歇即菩提」，当你觉察到枷锁只是虚幻的投射，它便开始瓦解。此刻请坚定地斩断执念的锁链，但也要温柔地看待自己，因为成长的过程需要慈悲。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (16, '高塔', 'upright', '高塔如同易经「震卦」的雷霆——突如其来的震动，打破虚假的稳固。你正经历一场颠覆，看似毁灭，实则为虚幻的结构画下句点。道家讲「飘风不终朝，骤雨不终日」，剧变之后必归于宁静。请信任这个过程：被震落的，都是不再真实的部分，而真实的你将在废墟中重生。', 'zh-CN'),
  (16, '高塔', 'reversed', '逆位的高塔提醒你：你可能正竭力避免一场必要的崩解，或灾难的冲击已过，正在余波中重整。东方智慧讲「祸兮福之所倚」，看似灾难的变故，往往隐藏着转机。请不要再修补摇摇欲坠的旧结构，允许必要的瓦解，让更真实、更稳固的基础得以建立。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (17, '星星', 'upright', '星星如同东方夜空中「北辰」的指引——在混沌与黑暗之后，希望的光芒重新升起。你正处于疗愈与重生的阶段，内心的渴望如星光般纯净而明亮。道家讲「上善若水」，此刻应以温柔与信心面对未来，相信宇宙的善意，让希望之光引领你穿越迷惘，朝向清明。', 'zh-CN'),
  (17, '星星', 'reversed', '逆位的星星提醒你：你可能正感到希望渺茫，或对未来失去信心，内心的光被云雾遮蔽。东方智慧讲「天行健，君子以自强不息」——即使在最深的暗夜，星辰依然存在。请不要放弃内心的信念，先从微小的事物中重新找回希望，让那点星光重新点亮你的旅程。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (18, '月亮', 'upright', '月亮如同东方智慧中的「阴」的奥秘——潜意识、幻象与未明之境。你正处于一个模糊不清的阶段，眼前的事物可能并非表面所见。道家讲「惚兮恍兮，其中有象」，月亮之下，真相隐而未显。此时不宜妄下判断，请信任直觉，但也保持觉察，待云开月明之日再作定夺。', 'zh-CN'),
  (18, '月亮', 'reversed', '逆位的月亮是迷雾散去的征兆——你正从幻象与恐惧中走出来，真相逐渐显现。如同易经「明夷」卦的「利艰贞」，暗夜将尽，黎明将至。请继续保持觉察，那些曾让你恐惧的事物，往往在看清之后发现并不可怕。当你穿越了内心的迷惘，便获得更深的清明。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (19, '太阳', 'upright', '太阳如同「阳」的极致光辉——万物显明，生机盎然。你正处于一段光明而丰盛的时期，能量充沛，所行之事皆能显化。道家讲「阳明」之道，此刻应敞开心胸，尽情享受生命的美好与温暖，同时以这份光明照亮他人。顺应这股向上的能量，让它自然绽放。', 'zh-CN'),
  (19, '太阳', 'reversed', '逆位的太阳提醒你：光明可能被暂时遮蔽，或你过度张扬而忽略了内在的平衡。东方智慧讲「亢龙有悔」——阳极而阴生，过度的光明也可能灼伤自己。请在喜悦中保持谦逊，在成就中不忘回归内在的宁静，让阳光既温暖他人，也照亮自己。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (20, '审判', 'upright', '审判如同易经「复卦」的「一阳来复」——觉醒与重生的召唤。你正面临一个深刻的内在召唤，过去的经验在此刻被重新审视与整合，获得新的意义。道家讲「返本归源」，这是一个与真实自我重逢的时刻。请聆听内心的召唤，宽恕过去，迎接重生，让生命进入新的篇章。', 'zh-CN'),
  (20, '审判', 'reversed', '逆位的审判提醒你：你可能正抗拒内在的召唤，或无法原谅自己与他人，让过去成为前行的包袱。东方智慧讲「放下屠刀，立地成佛」——觉悟只在当下一念。请停止自我批判，允许自己重新开始。当你愿意诚实面对内心的声音，便已走在重生的路上。', 'zh-CN');
INSERT INTO eastern_interpretations (card_id, card_name, orientation, interpretation, language) VALUES
  (21, '世界', 'upright', '世界如同易经「既济」之后的圆满，也如同太极的完成——一个循环的圆满完成。你正处于一个阶段性的完成与整合，过去的努力在此刻开花结果。道家讲「功成身退」，圆满之后，不是停滞，而是准备迎接新的循环。请先完整地体验这份成就与圆满，然后以清明之心，开启下一个旅程。', 'zh-CN'),
  (21, '世界', 'reversed', '逆位的世界提醒你：你可能已接近圆满却迟迟无法完成，或对即将到来的「完成」感到不安。东方智慧讲「物极必反，周而复始」——圆满不是终点，而是下一个循环的起点。请检视是什么让你在最后一步犹豫，放下对「完美」的执着，勇敢地跨越终点线，迎接新的开始。', 'zh-CN');

-- 驗證
SELECT language, COUNT(*) AS total
FROM eastern_interpretations
GROUP BY language
ORDER BY language;
